name: Release
on:
  push:
    tags:
        - 'v[0-9]+.*'

jobs:
    release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

                # Windows-specific OpenSSL setup
            - name: Install OpenSSL (Windows)
              if: matrix.os == 'windows-latest'
              run: |
                vcpkg integrate install
                vcpkg install openssl:x64-windows-static-md

            - name: Install dependencies
              run: |
                rustup target add wasm32-unknown-unknown
                cargo install trunk

            - name: Install Linux dependencies
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.0-dev \
                    build-essential \
                    curl \
                    wget \
                    libssl-dev \
                    libgtk-3-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - name: Build Tauri App
              uses: tauri-apps/tauri-action@v0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                # Only set OpenSSL vars for Windows
                OPENSSL_DIR: ${{ matrix.os == 'windows-latest' && 'C:/vcpkg/installed/x64-windows-static-md' || '' }}
                VCPKG_ROOT: ${{ matrix.os == 'windows-latest' && 'C:/vcpkg' || '' }}
                # Add pkg-config for Linux OpenSSL detection
                PKG_CONFIG_PATH: ${{ matrix.os == 'ubuntu-latest' && '/usr/lib/pkgconfig' || '' }}
              with: 
                tagName: ${{ github.ref_name }}
                releaseName: 'v__VERSION__'
                releaseBody: 'See the assets to download this version and install'
                releaseDraft: true
                prerelease: false

            